@startuml
title Crear tienda
actor Cliente
box "Frontend"
control RestaurantAbmComponent

Cliente->RestaurantAbmComponent: createRestaurant(formData)
RestaurantAbmComponent->restaurantService:create({ name, phone_number...})
activate restaurantService
end box
box "Backend"
control Router
restaurantService->Router: POST /v1/restaurants { name, phone_number...}
activate Router
control restaurants
Router->restaurants:createRestaurant({ name, phone_number...}) 
activate restaurants
restaurants->RestaurantsRepository: create({ name, phone_number...})
activate RestaurantsRepository
entity Restaurant
RestaurantsRepository->Restaurant: create({ name, phone_number...})
activate Restaurant
Restaurant-->"RestaurantsRepository": restaurant
deactivate Restaurant
RestaurantsRepository-->restaurants: resturant
deactivate RestaurantsRepository
end box
"restaurants"-->Router: return restaurant
deactivate restaurants
Router-->restaurantService: return restaurant
restaurantService-->RestaurantAbmComponent: return restaurant
deactivate restaurantService
RestaurantAbmComponent-->"Cliente": callSnackBar("El restaurant fue creado correctamente!")
@enduml