@startuml
title Crear tienda
actor Cliente
box "Frontend"
control RestaurantGridComponent
boundary "IU RestaurantGridComponent"
Cliente-> RestaurantGridComponent: 1.get()
activate RestaurantGridComponent
RestaurantGridComponent->"IU RestaurantGridComponent": 1.1 template
activate "IU RestaurantGridComponent"
"IU RestaurantGridComponent"-->RestaurantGridComponent: restaurant.grid.component.html
deactivate "IU RestaurantGridComponent"
RestaurantGridComponent-->Cliente: render
deactivate RestaurantGridComponent
Cliente-> RestaurantGridComponent: 2.openDialogRestaurant('create', null)
activate RestaurantGridComponent
control RestaurantAbmComponent
RestaurantGridComponent->RestaurantAbmComponent: 2.1 open(data)
activate RestaurantAbmComponent
boundary "IU RestaurantAbmComponent"
RestaurantAbmComponent->"IU RestaurantAbmComponent": 2.2 template(title, subtitle, btnColor, btnText, etc)
activate "IU RestaurantAbmComponent"
"IU RestaurantAbmComponent"->RestaurantAbmComponent: restaurant-grid.component.html
deactivate "IU RestaurantAbmComponent"
RestaurantAbmComponent-->Cliente: render
deactivate RestaurantAbmComponent
Cliente->RestaurantAbmComponent: create(formData)
activate RestaurantAbmComponent
RestaurantAbmComponent->RestaurantGridComponent: createRestaurant(formData)
deactivate RestaurantAbmComponent
RestaurantGridComponent->restaurantService:create({ name, phone_number, address, province_id, currency_symbol, user_id})
activate restaurantService
end box
box "Backend"
restaurantService->"POST /v1/restaurants": body
activate "POST /v1/restaurants"
control restaurants
"POST /v1/restaurants"->restaurants: create(body)
activate restaurants
restaurants->RestaurantsRepository: create(body)
activate RestaurantsRepository
entity Restaurant
RestaurantsRepository->Restaurant: create(body)
activate Restaurant
Restaurant-->"RestaurantsRepository": restaurant
deactivate Restaurant
RestaurantsRepository-->restaurants: resturant
deactivate RestaurantsRepository
end box
restaurants-->"POST /v1/restaurants": return res.status(200).json(restaurant)
deactivate restaurants
"POST /v1/restaurants"-->restaurantService: res.status(200).json(restaurant)
deactivate "POST /v1/restaurants"
restaurantService-->RestaurantGridComponent: return restaurant
deactivate restaurantService
RestaurantGridComponent-->"Cliente": callSnackBar("El restaurant fue creado correctamente!")
@enduml