@startuml
title Crear tienda
actor Cliente
box "Frontend"
control RestaurantAbmComponent

Cliente->RestaurantAbmComponent: createRestaurant(formData)
RestaurantAbmComponent->restaurantService:create({ name, phone_number...})
activate restaurantService
end box
box "Backend"
control restaurants
restaurantService->restaurants: POST /v1/restaurants { name, phone_number...}
activate restaurants
restaurants->RestaurantsRepository: create({ name, phone_number...})
activate RestaurantsRepository
entity Restaurant
RestaurantsRepository->Restaurant: create({ name, phone_number...})
activate Restaurant
Restaurant-->"RestaurantsRepository": restaurant
deactivate Restaurant
RestaurantsRepository-->restaurants: resturant
deactivate RestaurantsRepository
end box
deactivate restaurants
"restaurants"-->restaurantService: return restaurant
restaurantService-->RestaurantAbmComponent: return restaurant
deactivate restaurantService
RestaurantAbmComponent-->"Cliente": callSnackBar("El restaurant fue creado correctamente!")
@enduml