@startuml
title Iniciar sesion
actor Cliente
box "Frontend"
control LoginComponent
Cliente-> LoginComponent: login(email, password)
activate LoginComponent
LoginComponent->userService:login(email, password)
activate userService
end box
box "Backend"
control users
"userService"->users: /POST /v1/auth (email, password)
activate users
users->UsersRepository: auth(email)
activate UsersRepository
entity User
UsersRepository->User: findOne(email)
activate User
User-->"UsersRepository": user
deactivate User
UsersRepository-->users: user
deactivate UsersRepository
users->users: compare(req.body.password, user.password)
users-->userService: return(token, user)
deactivate users
userService-->LoginComponent: return(token, user)
deactivate userService
LoginComponent-->"Cliente": redirect "/home"
deactivate LoginComponent

@enduml